---
- name: "configuring docker secrets [{{ service.name }}]"
  tags: "{{ service.name }}"
  block:
    - name: "creating new secret [{{ service.name }}]"
      include_tasks: create-secret.yml

  rescue:
    - name: (docker secret err) removing old service
      community.docker.docker_swarm_service:
        name: "{{ service.name }}"
        state: absent

    - name: "creating new secret [{{ service.name }}]"
      include_tasks: create-secret.yml