galaxy_info:
  role_name: preconfig
  description: setting up docker and additional environment
  author: grnx
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions: 
      - all
  
