---
- name: installing additional packages
  become: true
  block:
    - name: installing docker packages
      block:
        - name: installing packages
          ansible.builtin.apt:
            name:
              - python3
              - python3-pip
            state: present
            update_cache: true

        - name: installing python packages by pip
          ansible.builtin.pip:
            name: docker
            executable: pip3
