version: "3.9"
services:
  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - kafka
      - kafka2
      - kafka-ui
      - zookeeper