version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    container_name: app
    ports:
    - 3001:80
    networks:
    - myNetwork
  